export default {
  entryPagePath: 'pages/login/index',
  pages: [
    'pages/login/index',
    'pages/index/index',
    'pages/menu-plan/index',
    'pages/tasks/index',
    'pages/analysis/index',
    'pages/dishes/index',
    'pages/ingredients/index',
    'pages/my/index',
    'pages/store-manage/index',
    'pages/staff-manage/index',
    'pages/dish-edit/index',
    'pages/daily-report/index',
    'pages/inventory/index',
    'pages/operation-log/index',
    'pages/audit/index',
    'pages/data-import/index',
    'pages/algorithm-config/index',
    'pages/menu-standard/index',
    'pages/dishes-detail/index',
  ],
  window: {
    navigationBarTitleText: '快餐厨房',
    navigationBarBackgroundColor: '#fff8ef',
    navigationBarTextStyle: 'black',
    backgroundTextStyle: 'light',
  },
  style: 'v2',
  sitemapLocation: 'sitemap.json',
};
